package org.fiveguns.po;

import java.util.Date;

public class DeliveryDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.id
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.time
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.goodid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    private Integer goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.number
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.operatorid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    private Integer operatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.deptid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.defaultnum
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    private Integer defaultnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.comments
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery.deliveryid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    private String deliveryid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.id
     *
     * @return the value of delivery.id
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.id
     *
     * @param id the value for delivery.id
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.time
     *
     * @return the value of delivery.time
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.time
     *
     * @param time the value for delivery.time
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.goodid
     *
     * @return the value of delivery.goodid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.goodid
     *
     * @param goodid the value for delivery.goodid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.number
     *
     * @return the value of delivery.number
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.number
     *
     * @param number the value for delivery.number
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.operatorid
     *
     * @return the value of delivery.operatorid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public Integer getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.operatorid
     *
     * @param operatorid the value for delivery.operatorid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public void setOperatorid(Integer operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.deptid
     *
     * @return the value of delivery.deptid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.deptid
     *
     * @param deptid the value for delivery.deptid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.defaultnum
     *
     * @return the value of delivery.defaultnum
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public Integer getDefaultnum() {
        return defaultnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.defaultnum
     *
     * @param defaultnum the value for delivery.defaultnum
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public void setDefaultnum(Integer defaultnum) {
        this.defaultnum = defaultnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.comments
     *
     * @return the value of delivery.comments
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.comments
     *
     * @param comments the value for delivery.comments
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery.deliveryid
     *
     * @return the value of delivery.deliveryid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public String getDeliveryid() {
        return deliveryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery.deliveryid
     *
     * @param deliveryid the value for delivery.deliveryid
     *
     * @mbggenerated Sat Sep 26 15:10:51 CST 2015
     */
    public void setDeliveryid(String deliveryid) {
        this.deliveryid = deliveryid == null ? null : deliveryid.trim();
    }
}