package org.fiveguns.po;

public class GoodsConsumeDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsconsume.id
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsconsume.staffid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Integer staffid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsconsume.goodid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Integer goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsconsume.number
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsconsume.id
     *
     * @return the value of goodsconsume.id
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsconsume.id
     *
     * @param id the value for goodsconsume.id
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsconsume.staffid
     *
     * @return the value of goodsconsume.staffid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Integer getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsconsume.staffid
     *
     * @param staffid the value for goodsconsume.staffid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setStaffid(Integer staffid) {
        this.staffid = staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsconsume.goodid
     *
     * @return the value of goodsconsume.goodid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsconsume.goodid
     *
     * @param goodid the value for goodsconsume.goodid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsconsume.number
     *
     * @return the value of goodsconsume.number
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsconsume.number
     *
     * @param number the value for goodsconsume.number
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}