package org.fiveguns.po;

public class StaffDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.id
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.name
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.gender
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.deptid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Integer deptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.id
     *
     * @return the value of staff.id
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.id
     *
     * @param id the value for staff.id
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.name
     *
     * @return the value of staff.name
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.name
     *
     * @param name the value for staff.name
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.gender
     *
     * @return the value of staff.gender
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.gender
     *
     * @param gender the value for staff.gender
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.deptid
     *
     * @return the value of staff.deptid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.deptid
     *
     * @param deptid the value for staff.deptid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }
}