package org.fiveguns.po;

import java.util.Date;

public class StorageDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.id
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.time
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.goodid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Integer goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.number
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.supplycompany
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private String supplycompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.supplier
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.phone
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.operatorid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private Integer operatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.comments
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.storageid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    private String storageid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.id
     *
     * @return the value of storage.id
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.id
     *
     * @param id the value for storage.id
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.time
     *
     * @return the value of storage.time
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.time
     *
     * @param time the value for storage.time
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.goodid
     *
     * @return the value of storage.goodid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.goodid
     *
     * @param goodid the value for storage.goodid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.number
     *
     * @return the value of storage.number
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.number
     *
     * @param number the value for storage.number
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.supplycompany
     *
     * @return the value of storage.supplycompany
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public String getSupplycompany() {
        return supplycompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.supplycompany
     *
     * @param supplycompany the value for storage.supplycompany
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setSupplycompany(String supplycompany) {
        this.supplycompany = supplycompany == null ? null : supplycompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.supplier
     *
     * @return the value of storage.supplier
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.supplier
     *
     * @param supplier the value for storage.supplier
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.phone
     *
     * @return the value of storage.phone
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.phone
     *
     * @param phone the value for storage.phone
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.operatorid
     *
     * @return the value of storage.operatorid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public Integer getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.operatorid
     *
     * @param operatorid the value for storage.operatorid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setOperatorid(Integer operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.comments
     *
     * @return the value of storage.comments
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.comments
     *
     * @param comments the value for storage.comments
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.storageid
     *
     * @return the value of storage.storageid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public String getStorageid() {
        return storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.storageid
     *
     * @param storageid the value for storage.storageid
     *
     * @mbggenerated Sat Sep 26 15:34:39 CST 2015
     */
    public void setStorageid(String storageid) {
        this.storageid = storageid == null ? null : storageid.trim();
    }
}